[package]
edition = "2021"
name    = "thrill_digger"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term    = "0.12.1"
combinations = "0.1.0"
rayon        = "1.5.1"
